routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Front Routes
 */
Route::get('/', 'FrontController@indexFront')->name('/');
Route::get('/home', 'FrontController@indexFront')->name('home');

Route::get('careers', 'FrontController@careers')->name('careers');

Route::get('careers/internal', 'FrontController@careersInternal')->name('careers-internal');


Route::get('viewJob/{id}', 'FrontController@viewJob')->name('viewJob');
Route::get('thankyou', 'FrontController@thankyou')->name('thankyou');


/**
 * Should be authenticated to apply a job
 */

Route::group(['middleware' => ['auth']], function () {
    //Personal Information
    Route::get('applyForm/{id}/personal-information', 'FrontController@applyForm')->name('applyForm');
    Route::post('applyFormPost/{id}/personal-information', 'FrontController@applyFormPost')->name('applyFormPost');
    Route::post('applyForm/{id}/personal-information', 'FrontController@savePersonalInformation')->name('application.storePI');
    Route::patch('applyForm/{id}/personal-information', 'FrontController@updatePersonalInformation')->name('application.updatePI');

    //Education
    Route::get('applyForm/application/{id}/education', 'FrontController@applyFormEducation')->name('applyForm.education');
    Route::post('applyForm/application/{id}/education', 'FrontController@saveEducation')->name('applyForm.saveEducation');
    Route::patch('applyForm/application/{id}/education', 'FrontController@updateEducation')->name('applyForm.updateEducation');


    //Experience
    Route::get('applyForm/application/{id}/experience', 'FrontController@applyFormExperience')->name('applyForm.experience');
    Route::post('applyForm/application/{id}/experience', 'FrontController@saveExperience')->name('applyForm.saveExperience');
    Route::patch('applyForm/application/{id}/experience', 'FrontController@updateExperience')->name('applyForm.updateExperience');

    //Skills
    Route::get('applyForm/application/{id}/skills', 'FrontController@applyFormSkills')->name('applyForm.skills');
    Route::post('applyForm/application/{id}/skills', 'FrontController@saveSkills')->name('applyForm.saveSkills');
    Route::patch('applyForm/application/{id}/skills', 'FrontController@updateSkills')->name('applyForm.updateSkills');

    //References
    Route::get('applyForm/application/{id}/references', 'FrontController@applyFormReferences')->name('applyForm.references');
    Route::post('applyForm/application/{id}/references', 'FrontController@saveReferences')->name('applyForm.saveReferences');
    Route::patch('applyForm/application/{id}/references', 'FrontController@updateReferences')->name('applyForm.updateReferences');

    //Languages
    Route::get('applyForm/application/{id}/languages', 'FrontController@applyFormLanguages')->name('applyForm.languages');
    Route::post('applyForm/application/{id}/languages', 'FrontController@saveLanguages')->name('applyForm.saveLanguages');
    Route::patch('applyForm/application/{id}/languages', 'FrontController@updateLanguages')->name('applyForm.updateLanguages');

    //Resume
    Route::get('applyForm/application/{id}/resume', 'FrontController@applyFormResume')->name('applyForm.resume');
    Route::post('applyForm/application/{id}/resume', 'FrontController@saveResume')->name('applyForm.saveResume');
    Route::patch('applyForm/application/{id}/resume', 'FrontController@updateResume')->name('applyForm.updateResume');


});


/**
 * Auth routes
 */
Auth::routes();


/**
 * Dashboard Routes, only admin can see
 */

Route::group(['middleware' => ['permission:dashboard']], function () {

    Route::resource('users', 'UsersController');

    Route::get('dashboard', 'HomeController@index')->name('dashboard');

    Route::resource('jobs', 'JobsController');

    Route::resource('applications', 'ApplicationsController');

    Route::resource('educations', 'EducationsController');

    Route::resource('references', 'ReferencesController');

    Route::resource('languages', 'LanguagesController');

    Route::resource('workExperiences', 'WorkExperiencesController');

    Route::resource('requestAds', 'RequestAdsController');

    Route::resource('options', 'OptionsController');

    Route::get('/requestAds/{id}','RequestAdsController@requestAd')->name('requestAd.create');

    //Add/show tags for reject, save and add to short list applications
    Route::get('applications/reject/{id}', 'ApplicationsController@reject')->name('reject');
    Route::get('applications/shortlist/{id}', 'ApplicationsController@addShortList')->name('shortList');
    Route::get('applications/saved/{id}', 'ApplicationsController@saveForLater')->name('saveForLater');


    Route::get('applications/saved', 'ApplicationsController@indexSavedForLater')->name('applications.indexSaved');
    Route::get('applications/shortlist', 'ApplicationsController@indexShortList')->name('applications.indexShortList');
    Route::get('applications/rejected', 'ApplicationsController@indexSavedForLater')->name('applications.indexRejected');



});

app/Models/WorkExperiences.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class WorkExperiences
 * @package App\Models
 * @version November 18, 2019, 7:51 pm UTC
 *
 * @property \App\Models\Applications application
 * @property string employer_name
 * @property string position
 * @property string responsabilities
 * @property string supervisors_name
 * @property string position_start_date
 * @property string position_end_date
 * @property string reason_leaving
 * @property string phone
 * @property string addresss
 * @property integer application_id
 */
class WorkExperiences extends Model
{
    use SoftDeletes;

    public $table = 'work_experiences';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'employer_name',
        'position',
        'responsabilities',
        'supervisors_name',
        'position_start_date',
        'position_end_date',
        'reason_leaving',
        'phone',
        'address',
        'application_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'employer_name' => 'string',
        'position' => 'string',
        'responsabilities' => 'string',
        'supervisors_name' => 'string',
        'position_start_date' => 'date',
        'position_end_date' => 'date',
        'reason_leaving' => 'string',
        'phone' => 'string',
        'address' => 'string',
        'application_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'application_id' => 'required',
        'employer_name' => 'required',
        'position' => 'required',
        'responsabilities' => 'required|max:2000',
        'supervisors_name' => 'required',
        'position_start_date' => 'required',
        'position_end_date' => 'required',
        'reason_leaving' => 'required|max:2000',
        'phone' => 'required',
        'address' => 'required',
    ];
    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function application()
    {
        return $this->belongsTo(\App\Models\Applications::class, 'application_id');
    }
}

app/Http/Controllers/WorkExperiencesController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\WorkExperiencesDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateWorkExperiencesRequest;
use App\Http\Requests\UpdateWorkExperiencesRequest;
use App\Repositories\WorkExperiencesRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class WorkExperiencesController extends AppBaseController
{
    /** @var  WorkExperiencesRepository */
    private $workExperiencesRepository;

    public function __construct(WorkExperiencesRepository $workExperiencesRepo)
    {
        $this->workExperiencesRepository = $workExperiencesRepo;
    }

    /**
     * Display a listing of the WorkExperiences.
     *
     * @param WorkExperiencesDataTable $workExperiencesDataTable
     * @return Response
     */
    public function index(WorkExperiencesDataTable $workExperiencesDataTable)
    {
        return $workExperiencesDataTable->render('work_experiences.index');
    }

    /**
     * Show the form for creating a new WorkExperiences.
     *
     * @return Response
     */
    public function create()
    {
        return view('work_experiences.create');
    }

    /**
     * Store a newly created WorkExperiences in storage.
     *
     * @param CreateWorkExperiencesRequest $request
     *
     * @return Response
     */
    public function store(CreateWorkExperiencesRequest $request)
    {
        $input = $request->all();

        $workExperiences = $this->workExperiencesRepository->create($input);

        Flash::success('Work Experiences saved successfully.');

        return redirect(route('workExperiences.index'));
    }

    /**
     * Display the specified WorkExperiences.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $workExperiences = $this->workExperiencesRepository->find($id);

        if (empty($workExperiences)) {
            Flash::error('Work Experiences not found');

            return redirect(route('workExperiences.index'));
        }

        return view('work_experiences.show')->with('workExperiences', $workExperiences);
    }

    /**
     * Show the form for editing the specified WorkExperiences.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $workExperiences = $this->workExperiencesRepository->find($id);

        if (empty($workExperiences)) {
            Flash::error('Work Experiences not found');

            return redirect(route('workExperiences.index'));
        }

        return view('work_experiences.edit')->with('workExperiences', $workExperiences);
    }

    /**
     * Update the specified WorkExperiences in storage.
     *
     * @param  int              $id
     * @param UpdateWorkExperiencesRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateWorkExperiencesRequest $request)
    {
        $workExperiences = $this->workExperiencesRepository->find($id);

        if (empty($workExperiences)) {
            Flash::error('Work Experiences not found');

            return redirect(route('workExperiences.index'));
        }

        $workExperiences = $this->workExperiencesRepository->update($request->all(), $id);

        Flash::success('Work Experiences updated successfully.');

        return redirect(route('workExperiences.index'));
    }

    /**
     * Remove the specified WorkExperiences from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $workExperiences = $this->workExperiencesRepository->find($id);

        if (empty($workExperiences)) {
            Flash::error('Work Experiences not found');

            return redirect(route('workExperiences.index'));
        }

        $this->workExperiencesRepository->delete($id);

        Flash::success('Work Experiences deleted successfully.');

        return redirect(route('workExperiences.index'));
    }
}

resources/views/work_experiences/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Work Experiences
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'workExperiences.store']) !!}

                        @include('work_experiences.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/work_experiences/datatables_actions.blade.php
{!! Form::open(['route' => ['workExperiences.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('workExperiences.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('workExperiences.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/work_experiences/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Work Experiences
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($workExperiences, ['route' => ['workExperiences.update', $workExperiences->id], 'method' => 'patch']) !!}

                        @include('work_experiences.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/work_experiences/fields.blade.php
<!-- Employer Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('employer_name', 'Employer Name:') !!}
    {!! Form::text('employer_name', null, ['class' => 'form-control']) !!}
</div>

<!-- Position Field -->
<div class="form-group col-sm-6">
    {!! Form::label('position', 'Position:') !!}
    {!! Form::text('position', null, ['class' => 'form-control']) !!}
</div>

<!-- Responsabilities Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('responsabilities', 'Responsabilities:') !!}
    {!! Form::textarea('responsabilities', null, ['class' => 'form-control','maxlength'=>'2000']) !!}
</div>

<!-- Supervisors Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('supervisors_name', 'Supervisors Name:') !!}
    {!! Form::text('supervisors_name', null, ['class' => 'form-control']) !!}
</div>

<!-- Position Start Date Field -->
<div class="form-group col-sm-6">
    {!! Form::label('position_start_date', 'Position Start Date:') !!}
    {!! Form::date('position_start_date', null, ['class' => 'form-control','id'=>'position_start_date']) !!}
</div>

@section('scripts')
    <script type="text/javascript">
        $('#position_start_date').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: false
        })
    </script>
@endsection

<!-- Position End Date Field -->
<div class="form-group col-sm-6">
    {!! Form::label('position_end_date', 'Position End Date:') !!}
    {!! Form::date('position_end_date', null, ['class' => 'form-control','id'=>'position_end_date']) !!}
</div>

@section('scripts')
    <script type="text/javascript">
        $('#position_end_date').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss',
            useCurrent: false
        })
    </script>
@endsection

<!-- Reason Leaving Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('reason_leaving', 'Reason Leaving:') !!}
    {!! Form::textarea('reason_leaving', null, ['class' => 'form-control','maxlength'=>'2000']) !!}
</div>

<!-- Phone Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone', 'Phone:') !!}
    {!! Form::text('phone', null, ['class' => 'form-control']) !!}
</div>

<!-- Addresss Field -->
<div class="form-group col-sm-6">
    {!! Form::label('addresss', 'Addresss:') !!}
    {!! Form::text('addresss', null, ['class' => 'form-control']) !!}
</div>

<!-- Application Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('application_id', 'Application Id:') !!}
    {!! Form::number('application_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('workExperiences.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/work_experiences/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Work Experiences</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('workExperiences.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('work_experiences.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/work_experiences/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Work Experiences
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('work_experiences.show_fields')
                    <a href="{!! route('workExperiences.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/work_experiences/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $workExperiences->id !!}</p>
</div>

<!-- Employer Name Field -->
<div class="form-group">
    {!! Form::label('employer_name', 'Employer Name:') !!}
    <p>{!! $workExperiences->employer_name !!}</p>
</div>

<!-- Position Field -->
<div class="form-group">
    {!! Form::label('position', 'Position:') !!}
    <p>{!! $workExperiences->position !!}</p>
</div>

<!-- Responsabilities Field -->
<div class="form-group">
    {!! Form::label('responsabilities', 'Responsabilities:') !!}
    <p>{!! $workExperiences->responsabilities !!}</p>
</div>

<!-- Supervisors Name Field -->
<div class="form-group">
    {!! Form::label('supervisors_name', 'Supervisors Name:') !!}
    <p>{!! $workExperiences->supervisors_name !!}</p>
</div>

<!-- Position Start Date Field -->
<div class="form-group">
    {!! Form::label('position_start_date', 'Position Start Date:') !!}
    <p>{!! $workExperiences->position_start_date !!}</p>
</div>

<!-- Position End Date Field -->
<div class="form-group">
    {!! Form::label('position_end_date', 'Position End Date:') !!}
    <p>{!! $workExperiences->position_end_date !!}</p>
</div>

<!-- Reason Leaving Field -->
<div class="form-group">
    {!! Form::label('reason_leaving', 'Reason Leaving:') !!}
    <p>{!! $workExperiences->reason_leaving !!}</p>
</div>

<!-- Phone Field -->
<div class="form-group">
    {!! Form::label('phone', 'Phone:') !!}
    <p>{!! $workExperiences->phone !!}</p>
</div>

<!-- Addresss Field -->
<div class="form-group">
    {!! Form::label('addresss', 'Addresss:') !!}
    <p>{!! $workExperiences->addresss !!}</p>
</div>

<!-- Application Id Field -->
<div class="form-group">
    {!! Form::label('application_id', 'Application Id:') !!}
    <p>{!! $workExperiences->application_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $workExperiences->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $workExperiences->updated_at !!}</p>
</div>

resources/views/work_experiences/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection