routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Front Routes
 */
Route::get('/', 'FrontController@indexFront')->name('/');
Route::get('/home', 'FrontController@indexFront')->name('home');

Route::get('careers', 'FrontController@careers')->name('careers');

Route::get('careers/internal', 'FrontController@careersInternal')->name('careers-internal');


Route::get('viewJob/{id}', 'FrontController@viewJob')->name('viewJob');
Route::get('thankyou', 'FrontController@thankyou')->name('thankyou');


/**
 * Should be authenticated to apply a job
 */

Route::group(['middleware' => ['auth']], function () {
    //Personal Information
    Route::get('applyForm/{id}/personal-information', 'FrontController@applyForm')->name('applyForm');
    Route::post('applyFormPost/{id}/personal-information', 'FrontController@applyFormPost')->name('applyFormPost');
    Route::post('applyForm/{id}/personal-information', 'FrontController@savePersonalInformation')->name('application.storePI');
    Route::patch('applyForm/{id}/personal-information', 'FrontController@updatePersonalInformation')->name('application.updatePI');

    //Education
    Route::get('applyForm/application/{id}/education', 'FrontController@applyFormEducation')->name('applyForm.education');
    Route::post('applyForm/application/{id}/education', 'FrontController@saveEducation')->name('applyForm.saveEducation');
    Route::patch('applyForm/application/{id}/education', 'FrontController@updateEducation')->name('applyForm.updateEducation');


    //Experience
    Route::get('applyForm/application/{id}/experience', 'FrontController@applyFormExperience')->name('applyForm.experience');
    Route::post('applyForm/application/{id}/experience', 'FrontController@saveExperience')->name('applyForm.saveExperience');
    Route::patch('applyForm/application/{id}/experience', 'FrontController@updateExperience')->name('applyForm.updateExperience');

    //Skills
    Route::get('applyForm/application/{id}/skills', 'FrontController@applyFormSkills')->name('applyForm.skills');
    Route::post('applyForm/application/{id}/skills', 'FrontController@saveSkills')->name('applyForm.saveSkills');
    Route::patch('applyForm/application/{id}/skills', 'FrontController@updateSkills')->name('applyForm.updateSkills');

    //References
    Route::get('applyForm/application/{id}/references', 'FrontController@applyFormReferences')->name('applyForm.references');
    Route::post('applyForm/application/{id}/references', 'FrontController@saveReferences')->name('applyForm.saveReferences');
    Route::patch('applyForm/application/{id}/references', 'FrontController@updateReferences')->name('applyForm.updateReferences');

    //Languages
    Route::get('applyForm/application/{id}/languages', 'FrontController@applyFormLanguages')->name('applyForm.languages');
    Route::post('applyForm/application/{id}/languages', 'FrontController@saveLanguages')->name('applyForm.saveLanguages');
    Route::patch('applyForm/application/{id}/languages', 'FrontController@updateLanguages')->name('applyForm.updateLanguages');

    //Resume
    Route::get('applyForm/application/{id}/resume', 'FrontController@applyFormResume')->name('applyForm.resume');
    Route::post('applyForm/application/{id}/resume', 'FrontController@saveResume')->name('applyForm.saveResume');
    Route::patch('applyForm/application/{id}/resume', 'FrontController@updateResume')->name('applyForm.updateResume');


});


/**
 * Auth routes
 */
Auth::routes();


/**
 * Dashboard Routes, only admin can see
 */

Route::group(['middleware' => ['permission:dashboard']], function () {

    Route::resource('users', 'UsersController');

    Route::get('dashboard', 'HomeController@index')->name('dashboard');

    Route::resource('jobs', 'JobsController');

    Route::resource('applications', 'ApplicationsController');

    Route::resource('educations', 'EducationsController');

    Route::resource('references', 'ReferencesController');

    Route::resource('languages', 'LanguagesController');

    Route::resource('workExperiences', 'WorkExperiencesController');

    Route::resource('requestAds', 'RequestAdsController');

    Route::resource('options', 'OptionsController');

    Route::get('/requestAds/{id}','RequestAdsController@requestAd')->name('requestAd.create');

    //Add/show tags for reject, save and add to short list applications
    Route::get('applications/reject/{id}', 'ApplicationsController@reject')->name('reject');
    Route::get('applications/shortlist/{id}', 'ApplicationsController@addShortList')->name('shortList');
    Route::get('applications/saved/{id}', 'ApplicationsController@saveForLater')->name('saveForLater');


    Route::get('applications/saved', 'ApplicationsController@indexSavedForLater')->name('applications.indexSaved');
    Route::get('applications/shortlist', 'ApplicationsController@indexShortList')->name('applications.indexShortList');
    Route::get('applications/rejected', 'ApplicationsController@indexSavedForLater')->name('applications.indexRejected');



});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <title>SolPretoleum Administrator</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css">
    <link rel="stylesheet" href="{{URL::to('/')}}/css/style.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Theme style -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/AdminLTE.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/skins/_all-skins.min.css">

    <!-- iCheck -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/square/_all.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css">

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">

    @yield('css')
</head>

<body class="skin-blue sidebar-mini">
@if (!Auth::guest())
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">

            <!-- Logo -->
            <a href="{{ url('/home') }}"> <img src="{{ asset('/images/sol-logo.png') }}" class="img-circle"
                                               alt="Logo"/></a>

            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->

                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">{!! Auth::user()->name !!}</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">

                                    <p>
                                        {!! Auth::user()->name !!}
                                        <small>Member since {!! Auth::user()->created_at->format('M. Y') !!}</small>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">

                                    <div class="pull-right">
                                        <a href="{!! url('/logout') !!}" class="btn btn-default btn-flat"
                                            onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                            Sign out
                                        </a>
                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
        @include('layouts.sidebar')
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @yield('content')
        </div>



    </div>
@else
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{!! url('/') !!}">
                    InfyOm Generator
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{!! url('/home') !!}">Home</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    <li><a href="{!! url('/login') !!}">Login</a></li>
                    <li><a href="{!! url('/register') !!}">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
    @endif

    <!-- jQuery 3.1.1 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/js/adminlte.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>

    @yield('scripts')
</body>
</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/menu.blade.php
<li class="{{ Request::is('users*') ? 'active' : '' }}">

    <a href="{!! route('users.index') !!}"><i class="fa fa-users"></i><span>Users</span></a>
</li>
<li class="{{ Request::is('jobs*') ? 'active' : '' }}">
    <a href="{!! route('jobs.index') !!}"><i class="fa fa-edit"></i><span>Post a Job</span></a>
</li>

<li class="{{ Request::is('requestAds*') ? 'active' : '' }}">
    <a href="{!! route('requestAds.index') !!}"><i class="fa fa-edit"></i><span>Request Ads</span></a>
</li>

<li class="{{ Request::is('applications*') ? 'active' : '' }}">
    <a href="{!! route('applications.index') !!}"><i class="fa fa-edit"></i><span>Jobs Applications</span></a>
</li>

<li class="{{ Request::is('options*') ? 'active' : '' }}">
    <a href="{!! route('options.index') !!}"><i class="fa fa-edit"></i><span>Options</span></a>
</li>



<!--
<li class="{{ Request::is('applications*') ? 'active' : '' }}">
    <a href="{!! route('applications.indexSaved') !!}"><i class="fa fa-edit"></i><span>Applications Saved</span></a>
</li>

<li class="{{ Request::is('applications*') ? 'active' : '' }}">
    <a href="{!! route('applications.indexShortList') !!}"><i class="fa fa-edit"></i><span>Applications Short List</span></a>
</li>

<li class="{{ Request::is('applications') ? 'active' : '' }}">
    <a href="{!! route('applications.indexRejected') !!}"><i class="fa fa-edit"></i><span>Applications Rejected</span></a>
</li>

-->

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar" id="sidebar-wrapper">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel user-side">
            <!--<div class="pull-left image">
                <img src="{{ asset('/images/sol-logo.png') }}" class="img-circle"
                     alt="Logo"/>
            </div>-->
            <div class="pull-left info">
                @if (Auth::guest())
                <p>SOlHR</p>
                @else
                    <p>{{ Auth::user()->name}}</p>
                @endif
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
          <span class="input-group-btn">
            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
            </div>
        </form>
        <!-- Sidebar Menu -->

        <ul class="sidebar-menu" data-widget="tree">
            @include('layouts.menu')
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>